config/routes.rb
Dreamline::Application.routes.draw do |map|
  get "authentication/index"
  get "authentication/create"
  get "authentication/destroy"

  resources :users
  resources :videos
  resources :comments
  
  root :to => "application#home"

  match 'video/most_popular'        => 'videos#list', :as => :most_popular_videos, :order=> "most popular", :page => "0"
  match 'video/latest'              => 'videos#list', :as => :latest_videos, :order=> "latest", :page => "0"
  match 'users/:id/videos'          => 'users#videos',:as => :user_videos, :page => "0"
  match 'video/latest/*page'        => 'videos#list', :as => :latest_videos, :order=> "latest"#, :requirements => { :page => /(['0'-'9']*)?/}
  match 'video/most_popular/*page'  => 'videos#list', :as => :most_popular_videos, :order=> "most popular" #, :requirements => { :page => /([0-9]*)?/}
  match 'users/:id/videos/*page'    => 'users#videos',:as => :user_videos

  Video::CATEGORIES.values.each do |order|
    match "video/#{order}"          => 'videos#list', :as => :category, :order => "#{order}", :page => "0"
    match "video/#{order}/*page"    => 'videos#list', :as => :category, :order => "#{order}" #, :requirements => { :page => /([0-9]*)?/}
  end

  match 'video/:id'                       => 'videos#show',        :as => :video, :requirements => { :id => /([0-9]*)?/ }
  match 'video/:id/edit'                  => 'videos#edit',        :as => :edit_video, :requirements => { :id => /([0-9]*)?/ }
  match 'video/:id/edit_tags(/new)'       => 'videos#edit_tags',   :as => :edit_video_tags, :requirements => { :id => /([0-9]*)?/ }
  match 'video/:id/update_tags(/new)'     => "videos#update_tags", :as => :update_video_tags
  match 'video/:id/update_video(/new)'    => "videos#update_video",:as => :update_video
  match 'video/:id/delete'                => "videos#destroy",     :as => :delete_video

  match 'fb/new'                          => 'fb_videos#new',             :as => :fb_video_upload
  match 'fb/create'                       => 'fb_videos#create',          :as => :fb_video_create
  match 'fb/list'                         => 'fb_videos#list',            :as => :fb_video_list
  match 'fb/vtaggees'                     => 'fb_videos#vtaggees',        :as => :fb_vtaggees
  match 'fb/about'                        => 'fb_videos#about',           :as => :fb_about
  match 'fb/:fb_id/'                      => 'fb_videos#show',            :as => :fb_show_video, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/edit'                  => 'fb_videos#edit',            :as => :fb_edit_video, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/edit_tags(/new)'       => 'fb_videos#edit_tags',       :as => :fb_edit_video_tags, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/update_tags(/new)'     => 'fb_videos#update_tags',     :as => :fb_update_video_tags, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/analyze'               => 'fb_videos#analyze',         :as => :fb_analyze_video, :requirements => { :fb_id => /([0-9]*)?/ }

  match 'users/:id/videos/*page'  => 'users#videos', :as => :user_videos

    match 'sign_up'     => 'users#new', :as => 'sign_up'
    match 'sign_in'     => 'sessions#new', :as => 'sign_in'
    match 'sign_out'    => 'sessions#destroy', :as => 'destroy'
    match 'auth'        => 'sessions#aoth_athenticate', :as => 'aoth'
    match 'auth_return' => 'sessions#aoth_athenticate_return', :as => 'aoth_return'
    match 'auth/:provider/callback' => 'authentication#get_uid_and_access_token'

  match 'about' => 'application#about', :as =>'about'

  
  

  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer(4)      not null, primary key
#  email              :string(255)     not null
#  password           :string(255)
#  nick               :string(255)
#  fb_id              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(128)
#  salt               :string(128)
#  confirmation_token :string(128)
#  remember_token     :string(128)
#  status             :integer(4)      not null
#

require 'carrierwave/orm/activerecord'

class User < ActiveRecord::Base
  include Clearance::User
  
  has_many :videos, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :authentications, :dependent => :destroy

  validates_presence_of :nick, :message => "must be entered."
  validates_uniqueness_of :nick, :message => "already taken."

  mount_uploader :profile_pic, ProfilePicUploader

#--------------------- Global params --------------------------
  FULL_USER_IMG_PATH = "#{Rails.root.to_s}/public/images/users/"
  USER_IMG_PATH = "/images/users/"
  IMG_PATH_PREFIX = "#{Rails.root.to_s}/public"
  DEFAULT_PROFILE_IMG = "#{USER_IMG_PATH}default_profile.png"
#------------------------------------------------------ Instance methods -------------------------------------------------------

#------------------------------------------------------ Class methods -------------------------------------------------------
  def self.profile_pic_directory(user_id)
    string_id = (user_id.to_s).rjust(9,"0")
    "#{USER_IMG_PATH}#{string_id[0..2]}/#{string_id[3..5]}/#{string_id[6..8]}"
  end
  
  def self.profile_pic_full_directory(user_id)
    string_id = (user_id.to_s).rjust(9,"0")
    "#{FULL_USER_IMG_PATH}#{string_id[0..2]}/#{string_id[3..5]}/#{string_id[6..8]}"
  end

  def self.profile_pic_src(user_id)
   pic_path = "#{User.profile_pic_directory(user_id)}/profile.jpg"
   (FileTest.exists? "#{IMG_PATH_PREFIX}#{pic_path}") ? pic_path : DEFAULT_PROFILE_IMG
  end

  def self.get_users_by_activity
    #Moozly: updae to users with latest video till a week ago + no zeros...
    Video.find_by_sql("select users.id, nick, count(user_id) as videos_num from videos, users where videos.user_id = users.id group by videos.user_id order by videos_num desc limit 3;")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :redirect_first_page_to_base
  before_filter :authorize_admins, :only => [:index, :edit]

  # GET /users
  # GET /users.xml
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    if signed_in? && current_user.id == params[:id] || (["elinor.dreamer@gmail.com", "klein.itay@gmail.com"].include? current_user.email)
      @user = User.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @user }
      end
    else
      redirect_to "/"
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    render_404
    #@user = User.new
    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.xml  { render :xml => @user }
    #end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    @user.status = 2 #for now active, later change to 1 - pre active

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def authorize_admins
    unless (["elinor.dreamer@gmail.com", "klein.itay@gmail.com"].include? current_user.email)
      render_404 and return
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  def videos
    @user = User.find(params[:id])
    if !@user then render_404 and return end
    current_page = (params[:page] == "0" ? "1" : params[:page]).to_i
    @user_videos_page = true
    @own_videos = current_user == @user ? true : false
    @page_title = @own_videos ? "My" : "#{@user.nick}'s"
    @empty_message = "This user does not have any videos yet."
    @videos = Video.get_videos_by_user(current_page,@user.id, false)
    get_sidebar_data # latest
    render "/videos/user_videos_list"
  end
  
  
  def get_sidebar_data
    @sidebar_order = "latest"
    @sidebar_list_title = "Latest Ones"
    @sidebar_videos = Video.get_videos_by_sort(1,@sidebar_order, true ,3)
    @trending_videos = Video.get_videos_by_sort(1,"popular", true ,3)
    @active_users = User.get_users_by_activity
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="signin-form">
		<ul>
			<li>
    			<%= f.label :email %>
					<span><%= f.text_field :email, :type => "email" %></span>
			</li>
			<li>
    		<%= f.label :password %>
				<span><%= f.password_field :password %></span>	
			</li>
			<li>
				<%= f.label :nickname %>
				<span><%= f.text_field :nick %></span>
			</li>
			<% if @user.new_record? %>
				<li>
					<div><label class="remem-me"><input type="checkbox"  />Remember Me </label></div>
				</li>
				<li>
					<div><a href="#" class="fb-connect">Connect With Fb</a></div>
				</li>
			<% end %>
			<li>
			   <%= f.submit %>
			</li>
		</ul>
		<ul>
			<li>
				<div>
					<% if @user.new_record? %>
						<%= link_to "Sign in", sign_in_path %>
					<% else %>
						<%= link_to 'Cancel', user_path %>
					<% end %>
				</div>
		  </li>
		</ul>
  </div>
 
<% end %>

app/views/users/edit.html.erb
<title>VtagO - Edit user</title>

<div id="signin_content_wrapper">
	<div id="signin_content">
		<div id="left_col">
			<div class="bg-shadow">&nbsp;<!--this is for side shadow --></div>
			<div>
				<h1>Edit account</h1>
				<p>Here you can edit your account details.</p>
			</div>
			<%= render 'form' %>
		</div>
		<div id="right_col">
			<a href="#">
				<img src="/images/banner-signin.jpg" alt="" />
			</a>
		</div>
		<br class="clear" />
	</div>
</div>

app/views/users/index.html.erb
<div id="signin_content_wrapper">
	<div id="signin_content">
		<h1>Listing users</h1>
		<table>
			<tr>
				<th>Email</th>
				<th>Password</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>

			<% @users.each do |user| %>
			<tr>
				<td><%= user.email %></td>
				<td><%= user.password %></td>
				<td><%= link_to 'Show', user %></td>
				<td><%= link_to 'Edit', edit_user_path(user) %></td>
				<td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
			</tr>
			<% end %>
		</table>

		<br />

		<%= link_to 'New User', "/sign_in" %>
	</div>
</div>

app/views/users/new.html.erb
<title>Sign up</title>

<!--Content Section -->
<div id="signin_content_wrapper">
	<div id="signin_content">
		<div id="left_col">
			<div class="bg-shadow">&nbsp;<!--this is for side shadow --></div>
			<div class="signup_form_heading">
				<h1>Create account</h1>
				<p>Welcome, please create your account or click on "Sign in" if you already have one.</p>
			</div>
			<%= render :partial => "users/form" %>
		</div>
		<div id="right_col">
			<a href="/sign_up">
				<img src="/images/banner-signin.jpg" alt="Sign Up" />
			</a>
		</div>
		<br class="clear" />
	</div>
</div>
<!--Content Section End -->

<%#=<h1>New user</h1> %>
<%#= link_to 'Back', users_path %>

app/views/users/show.html.erb
<title>VtagO - <%= @user.nick %></title>

<!--Content Section -->
<div id="signin_content_wrapper">
	<div id="signin_content">
		<div id="left_col">
			<div class="bg-shadow">&nbsp;<!--this is for side shadow --></div>
			<div class="signin_form_heading">
				<h2><%= @user.nick %>'s account</h2>
				<p id="notice"><%= notice %></p>
			</div>
			<p>
			  <b>Email:</b>
			  <%= @user.email %>
			</p>
			</br>
			<p>
			  <b>Nick:</b>
			  <%= @user.nick %>
			</p>
			</br>
			<%#= link_to 'Edit', edit_user_path(@user) %> <!--|-->
			<%= link_to 'My Videos', "#{@user.id}/videos" %>
		</div>
		<div id="right_col">
			<a href="#">
				<img src="/images/banner-signin.jpg" alt="" />
			</a>
		</div>
		<br class="clear" />
	</div>
</div>