config/routes.rb
Dreamline::Application.routes.draw do |map|
  get "authentication/index"
  get "authentication/create"
  get "authentication/destroy"

  resources :users
  resources :videos
  resources :comments
  
  root :to => "application#home"

  match 'video/most_popular'        => 'videos#list', :as => :most_popular_videos, :order=> "most popular", :page => "0"
  match 'video/latest'              => 'videos#list', :as => :latest_videos, :order=> "latest", :page => "0"
  match 'users/:id/videos'          => 'users#videos',:as => :user_videos, :page => "0"
  match 'video/latest/*page'        => 'videos#list', :as => :latest_videos, :order=> "latest"#, :requirements => { :page => /(['0'-'9']*)?/}
  match 'video/most_popular/*page'  => 'videos#list', :as => :most_popular_videos, :order=> "most popular" #, :requirements => { :page => /([0-9]*)?/}
  match 'users/:id/videos/*page'    => 'users#videos',:as => :user_videos

  Video::CATEGORIES.values.each do |order|
    match "video/#{order}"          => 'videos#list', :as => :category, :order => "#{order}", :page => "0"
    match "video/#{order}/*page"    => 'videos#list', :as => :category, :order => "#{order}" #, :requirements => { :page => /([0-9]*)?/}
  end

  match 'video/:id'                       => 'videos#show',        :as => :video, :requirements => { :id => /([0-9]*)?/ }
  match 'video/:id/edit'                  => 'videos#edit',        :as => :edit_video, :requirements => { :id => /([0-9]*)?/ }
  match 'video/:id/edit_tags(/new)'       => 'videos#edit_tags',   :as => :edit_video_tags, :requirements => { :id => /([0-9]*)?/ }
  match 'video/:id/update_tags(/new)'     => "videos#update_tags", :as => :update_video_tags
  match 'video/:id/update_video(/new)'    => "videos#update_video",:as => :update_video
  match 'video/:id/delete'                => "videos#destroy",     :as => :delete_video

  match 'fb/new'                          => 'fb_videos#new',             :as => :fb_video_upload
  match 'fb/create'                       => 'fb_videos#create',          :as => :fb_video_create
  match 'fb/list'                         => 'fb_videos#list',            :as => :fb_video_list
  match 'fb/vtaggees'                     => 'fb_videos#vtaggees',        :as => :fb_vtaggees
  match 'fb/about'                        => 'fb_videos#about',           :as => :fb_about
  match 'fb/:fb_id/'                      => 'fb_videos#show',            :as => :fb_show_video, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/edit'                  => 'fb_videos#edit',            :as => :fb_edit_video, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/edit_tags(/new)'       => 'fb_videos#edit_tags',       :as => :fb_edit_video_tags, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/update_tags(/new)'     => 'fb_videos#update_tags',     :as => :fb_update_video_tags, :requirements => { :fb_id => /([0-9]*)?/ }
  match 'fb/:fb_id/analyze'               => 'fb_videos#analyze',         :as => :fb_analyze_video, :requirements => { :fb_id => /([0-9]*)?/ }

  match 'users/:id/videos/*page'  => 'users#videos', :as => :user_videos

    match 'sign_up'     => 'users#new', :as => 'sign_up'
    match 'sign_in'     => 'sessions#new', :as => 'sign_in'
    match 'sign_out'    => 'sessions#destroy', :as => 'destroy'
    match 'auth'        => 'sessions#aoth_athenticate', :as => 'aoth'
    match 'auth_return' => 'sessions#aoth_athenticate_return', :as => 'aoth_return'
    match 'auth/:provider/callback' => 'authentication#get_uid_and_access_token'

  match 'about' => 'application#about', :as =>'about'

  
  

  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

 before_filter :redirect_first_page_to_base
 before_filter :authorize, :only => [:edit, :edit_tags]

	def show
		video_id = params[:id].to_i
		@video = Video.for_view(video_id) if video_id != 0
    @video.gen_player_file current_user
		if !@video then render_404 and return end
	  check_video_redirection(@video)
	  @user = @video.user
	  @own_videos = current_user == @user ? true : false
	  @comments, @total_comments_count = Comment.get_video_comments(video_id)

	  #sidebar
	  get_sidebar_data # latest
	  @user_videos = Video.get_videos_by_user(1, @user.id, true, 3)
	  @trending_videos = Video.get_videos_by_sort(1,"popular", true ,3)
	  @active_users = User.get_users_by_activity
	end
	
	def list
	  @videos = []
	  @order = params[:order]
	  current_page = (params[:page] == "0" ? "1" : params[:page]).to_i
	  case
      when @order == "most popular" || @order == "latest"
        @videos = Video.get_videos_by_sort(current_page, @order, false)
	    when key = Video::CATEGORIES.key(@order)
	      @videos = Video.get_videos_by_category(key)
	      @category = true
	    else
	      render_404 and return
    end
    @page_title = @order.titleize
    @empty_message = "There are no videos to present for this page."
    get_sidebar_data

  end

  def check_video_redirection(video)
    if request.path != video.uri
      redirect_to(request.request_uri.sub(request.path, video.uri), :status => 301)
    end  
  end

  def get_sidebar_data
    if @order == "latest"
      @sidebar_order = "most popular"
      @sidebar_list_title = "Trending Now"
    else
      @sidebar_order = "latest"
      @sidebar_list_title = "Latest Ones"
    end
    @sidebar_videos = Video.get_videos_by_sort(1,@sidebar_order, true ,3)
    @active_users = User.get_users_by_activity
  end

  def new
    @video = Video.new
  end

  def create
    unless !signed_in? || !params[:video]
      more_params = {:user_id => current_user.id, :duration => 0} #temp duration
      @video = Video.new(params[:video].merge(more_params))
      if @video.save
         @video.detect_and_convert(fb_graph)
         unless !@video.fbid.nil?
           @video.delay.upload_video_to_fb(fb_graph)
         end
        flash[:notice] = "Video has been uploaded"
        redirect_to "/video/#{@video.id}/edit_tags/new"
      else
        render 'new'
      end
    else
      redirect_to "/"
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def edit_tags
    @new = params[:new]=="new" ? true : false
    @video = Video.find(params[:id])
    @page_title = "#{@video.title.titleize} - #{@new ? "Add Tags" : "Edit"} Tags"
    @user = current_user
    @taggees = @video.video_taggees
    friends = fb_graph.get_connections(current_user.fb_id,'friends')
    @friends = {}
    friends.map {|friend| @friends[friend["name"]] = friend["id"]}
    @friends[current_user.nick] = current_user.fb_id
    @names_arr = @friends.keys
    @gallery_var=0 #this variable is used to count the number of boxes in the gallery in order to put dynamic class on the last box
    #@likes = graph.get_connections("me", "likes")
    #sidebar
	  get_sidebar_data # latest
	  @user_videos = Video.get_videos_by_user(1, @user.id, true, 3)
	  @trending_videos = Video.get_videos_by_sort(1,"popular", true ,3)
	  @active_users = User.get_users_by_activity
  end

  def update_video
    unless !signed_in? || !params[:video]
      @video = Video.find(params[:id])
      if @video.update_attributes(params[:video])
        redirect_to video_path @video
      end# if update_attributes
    else
      redirect_to "/"
    end
  end

  def update_tags
    unless !signed_in?
      @video = Video.find(params[:id])
      #---------------------there are at least one taggee left
      unless !params[:video]
        @new = params[:new]=="new" ? true : false
        existing_taggees = @video.video_taggees_uniq.map(&:fb_id)
        updated_taggees_ids = []
        updated_taggees_ids = params[:video][:existing_taggee_attributes].values.map!{|h| h["fb_id"].to_i}.uniq.reject{ |id| id==0 }
        if @video.update_attributes(params[:video])
          if updated_taggees_ids.any?
            if @new
              new_taggees = updated_taggees_ids
            else
              new_taggees = (updated_taggees_ids - existing_taggees)
            end
            post_vtag(@new, new_taggees, @video.id, @video.title.titleize)
          end #if ids
        end# if update_attributes
        #---------------------all taggees are removed
      else
        @video.delete_taggees
      end
      redirect_to video_path (@video)
    else
      redirect_to "/"
    end
  end

  def destroy
    video = Video.find(params[:id])
    fb_delete = false #currently seems unavailable option by FB!
    fb_delete ? graph = fb_graph : nil
    flash[:notice] = video.delete(fb_delete, graph)
    redirect_to "/users/#{current_user.id}/videos"
  end
end

app/helpers/videos_helper.rb
module VideosHelper

    def fields_for_taggee(taggee, &block)
        prefix = taggee.new_record? ? 'new' : 'existing'
        fields_for("video[#{prefix}_taggee_attributes][]", taggee, &block)
    end

    def add_taggee_link(name)
        link_to_function name do |page|
            page.insert_html :bottom, :VideoTaggees, :partial => 'video_taggees/video_taggee', :object => VideoTaggee.new
        end
    end
    
    def gallery_class_helper  
       if @gallery_var<2
          @gallery_var=@gallery_var+1
          @dynamic_class="edit_box_center"
       else
           @gallery_var=0
           @dynamic_class="edit_box_last"
       end
    end


end

app/views/videos/_list_sidebar.html.erb
<div id="right_content">
	<div class="sign-in-field">
		<input type="text" value="Search Video" class="txt-field"  onfocus="if(this.value == 'Search Video') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Search Video'; }" name="s" />
		<a href="#">Search Button</a>
	</div>

	<div class="banner-right">
		<a href="#"><img src="/images/banner-right.jpg" alt="" /></a>
		<h5>Join the most famous video-sharing community!</h5>
		<a href="#"><img src="/images/btn-join.gif" alt="" /></a>
	</div>
	<div class="classic-channel">
		<div class="heading-top">
			<h2>Classic Channels</h2>
		</div>
		<ul>
			<li>
				<a href="#" class="red">
					<img src="/images/img-c1.jpg" alt="" />
					<span>The woman in black</span>
					<em><strong>1,197,002</strong>  Members</em>
				</a>
			</li>
			<li>
				<a href="#" class="green">
					<img src="/images/img-c2.jpg" alt="" />
					<span>The Intention</span>
					<em><strong>1,197,002</strong>  Members</em> 
				</a>
			</li>
			<li>
				<a href="#" class="silver">
					<img src="/images/img-c3.jpg" alt="" />
					<span>Lenny</span>
					<em><strong>1,197,002</strong>  Members</em>
				</a>
			</li>
		</ul>
	</div>

	<br class="clear" />


	<div class="trending-box">
		<div class="heading-top">
			<h2>Trending Now</h2><a href="#">View More</a>
		</div>
		<ul>
			<li>
				<div class="video-box-trending">
					<img src="/images/img-tr-1.jpg" alt="" />
					<span class="time-video">08:53</span>
					<span class="add-playlist"></span>
				</div>
				<div class="text-desc-tre">
					<h5><a href="videodetail.html">Duis molestie nunc nec</a></h5>
					<p><strong>1,197,002</strong> views </p>
					<span>By <a href="#">Simon Cole</a></span>
				</div>
			</li>
			<li>
				<div class="video-box-trending">
					<img src="/images/img-tr-2.jpg" alt="" />
					<span class="time-video">08:53</span>
					<span class="add-playlist"></span>
				</div>
				<div class="text-desc-tre">
					<h5><a href="videodetail.html">Duis molestie nunc nec</a></h5>
					<p><strong>1,197,002</strong> views </p>
					<span>By <a href="#">Simon Cole</a></span>
				</div>
			</li>
			<li>
				<div class="video-box-trending">
					<img src="/images/img-tr-4.jpg" alt="" />
					<span class="time-video">08:53</span>
					<span class="add-playlist"></span>
				</div>
				<div class="text-desc-tre">
					<h5><a href="videodetail.html">Duis molestie nunc nec</a></h5>
					<p><strong>1,197,002</strong> views </p>
					<span>By <a href="#">Simon Cole</a></span>
				</div>
			</li>
		</ul>
	</div>

	<div class="event-box">
		<div class="heading-top">
			<h2>Events</h2><a href="#">View More</a>
		</div>

		<ul>
			<li>
				<div class="img-frame-event">
					<img src="/images/img-c1.jpg" alt="" />
				</div>
				<div class="text-desc-event">
					<h5>Duis molestie nunc les.</h5>
					<p>Duis molestie nunc nec felis sollicit udin sed ornare lorem varius.</p>
				</div>
			</li>
			<li>
				<div class="img-frame-event">
					<img src="/images/img-c2.jpg" alt="" />
				</div>
				<div class="text-desc-event">
					<h5>Duis molestie nunc les.</h5>
					<p>Duis molestie nunc nec felis sollicit udin sed ornare lorem varius.</p>
				</div>
			</li>
			<li>
				<div class="img-frame-event">
					<img src="/images/img-c3.jpg" alt="" />
				</div>
				<div class="text-desc-event">
					<h5>Duis molestie nunc les.</h5>
					<p>Duis molestie nunc nec felis sollicit udin sed ornare lorem varius.</p>
				</div>
			</li>
		</ul>
	</div>
</div>

app/views/videos/_player_frame.html.erb
	<div class="video-slider">
		<object type="application/x-shockwave-flash" style="width:629px; height:353px;" 				data="http://www.youtube.com/v/ag8UGlhQJ0o?fs=1&amp;hl=en_US&amp;rel=0">
			<param name="movie" value="http://www.youtube.com/v/ag8UGlhQJ0o?fs=1&amp;hl=en_US&amp;rel=0" />
			<param value="application/x-shockwave-flash" name="type" /> 
			<param value="true" name="allowfullscreen" /> 
			<param value="always" name="allowscriptaccess" /> 
			<param value="opaque" name="wmode" />
		</object>
	</div>

app/views/videos/_video_taggees.erb
<%= form_for(@video) do |video_form| %>
    <table>
        <% i = 0 %>
        <%= video_form.fields_for :tageeses do |taggee| %>
            <td>
                <%= render 'views/video_taggees/_new_taggee_box', :taggee => taggee %>
            </td>
        <% end %>
    </table>
<% end %>

app/views/videos/_videos_list.html.erb
<div class="video-category" id="tab1">
	<div class="heading-list">
		<h1><%= @page_title %> Videos</h1>
		<ul>
			<li class="show-grid">
				<a href="#" class="list-view">List View</a>
				<a href="#" class="grid-view">Grid View</a>
			</li>
		</ul>
	</div>

	<% if @videos.any? %>
		<div class="wrapper_list_view">
			<% @videos.each do |v| %>
				<div class="description-box nopadding">
					<div class="video-box">
						<a href="<%= v.uri %>">
							<img src= "<%= v.thumb %>" alt="<% v.title %>" />
							<span class="time-video"><%= nice_duration(v.duration) %></span>
						</a>
					</div>
					<div class="description-video">
						<div class="heading-date">
							<h5><a href="<%= v.uri %>"><%= v.title %></a></h5>
							<span><%= nice_time_ago_in_words_including_day_name(v.created_at) %></span>
						</div>
						<div class="text-desc">
							<p><%= v.description %></p>
						</div>
						<div class="total-views"><strong><%= v.views_count %></strong> views</div>
						<div class="bottom-panel">
							<ul> 
								<% if !@user_videos_page %>
								<li class="nobg">by: <a href="/users/<%= v.user_id %>/videos"><%= v.user_nick %></a></li>
								<% end %>
								<% if !@category %>
									<li><strong>Category: </strong> <a href=<%= v.category_uri %>><%= v.category_title %></a></li>
								<% end %>
								<li><strong><%= v.views_count %></strong> Views</li>
								<% comment_text = nice_how_many_comments(v.comments.count) %>
								<li><a href="<%= v.uri %>?comment=true&signed=<%= signed_in? %>#comment-area"> <%= comment_text %> </a></li>
							</ul>
							<!-- rating... -->
							<!--div class="rating-stars"><em>&nbsp;</em><em>&nbsp;</em><em>&nbsp;</em><em>&nbsp;</em><em class="low-rate">&nbsp;</em></div-->
								<!--a href="#" class="share-btn">!!Share This</a-->
							</div>
						</div>
					</div>
				<% end %>
			</div>
		<% else %>			
				<h2> <%= @empty_message %> </h2>
		<% end %>
	</div>

	<%= will_paginate @videos, {:class => "digg_pagination"} %>

	<!--div class="pager">
		<ul>
			<li><a href="#" class="pre">Previous</a></li>
			<li><a href="#" class="active">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><span>...</span></li>
			<li><a href="#">44</a></li>
			<li><a href="#" class="next">Next</a></li>
			<li><a href="#">Next</a></li>
		</ul>
	</div-->
</div>

app/views/videos/edit.html.erb
<div id="signin_content_wrapper">
    <div id="signin_content">
        <div id="left_col">
            <div class="bg-shadow">&nbsp;<!--this is for side shadow --></div>
            <div class="edit_form_heading">
                <h1>Upload Video</h1>

                <p>Edit video details</p>
            </div>
            <%= form_for @video, :url => :update_video do |f| %>
                <% if @video.errors.any? %>
                    <div id="error_explanation">
                        <ul>
                            <% @video.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>
                <div class="signin-form">
                    <table border="0">
                        <% if @likes %>
                            <% for like in @likes %>
                                <tr>
                                    <td><b><%= h like["name"] %> </b></td>
                                </tr>
                                <tr>
                                    <td><%= h like["category"] %></td>
                                </tr>
                                <tr>
                                    <td>&ndash;</td>
                                </tr>
                            <% end %>
                        <% end %>
                    </table>
                    <ul>
                        <li>
                            <%= f.label :title %>
                            <span><%= f.text_field :title %></span>
                        </li>
                        <li>
                            <%= f.label :description %>
                            <%= f.text_area :description, "onfocus"=>"this.value=''; setbg('#e5fff3')", "onblur"=>"setbg('white');" %>
                        </li>
                        <li>
                            <%= f.label :category %>
                            <%= f.select :category, options_for_select(Video::CATEGORIES.map { |k, v| [v.titleize, k] }) %>
                        </li>
                        <li>
                            <%= f.label :keywords %>
                            <span><%= f.text_field :keywords %></span>
                        </li>
                        <li> <%= f.submit 'Submit', :class=>"site_button radious_6 left"%>  <%= link_to 'Cancel', "/" ,:class=>'edit_cancel_link'%></li>
                    </ul>
                </div>
            <% end %>
        </div>

        <div id="right_col">
            <a href="#">
                <img src="/images/banner-signin.jpg" alt=""/>
            </a>
        </div>
        <br class="clear"/>
    </div>
</div>

<script type="text/javascript">
    function setbg(color) {
        document.getElementById("video_description").style.background = color
    }
</script>
</div>

app/views/videos/edit_taggees.html.erb
<%= form_for @video,  :html => { :method => 'put' } do |f| %>
    <div id="video_taggees">
        <% @video.video_taggees.each do |video_taggee| %>
            <%= render :partial => 'VideoTaggees/video_taggee', :locals => { :video_taggee => video_taggee } %>
        <% end %>
    </div>
    <p><%= submit_tag "Update Project" %></p>
    <p><%= add_taggee_link "Add a new tag" %></p>
<% end %>

app/views/videos/edit_tags.html.erb
<link type="text/css" href="/javascripts/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
<!--<script type="text/javascript" src="/javascripts/js/jquery-1.6.2.min.js"></script>-->
<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>-->
<script type="text/javascript" src="/javascripts/js/jquery-ui-1.8.16.custom.min.js"></script>

<head>
	<title>VtagO - <%= @page_title %></title>
	<script>
		$(document).ready(function(){
			$('.gallery_delete').hide();
			//toggel tag delete icon
			//this function is adjusted to the normal and appended items
			$('#tag_table').on('hover','.edit_box',function(){
				$(this).children().find('.gallery_delete').toggle();
			});
			//display the add new tags box
			$('#add_new_tag').click(function(){
				$('#new_tag').show();
				var new_tag_d=$("<div class='edit_box edit_box_new radious_6'><div class='left'><img src='/images/gallery_delete.png' class='gallery_delete'></div><div id='new_tag' class='avatar_border radious_6'><img src='/images/avatar.png' width='55' height='60'></div><label class ='new_tag_label' for='tags'>Add another Vtag</label><br><input type='text' class='contact_info'><input type='hidden' class='fb_id'></div>");
				new_tag_d.appendTo('#tag_table');
			});
			
			//remove the appended new tag div
			$('#tag_table').on('click','.gallery_delete',function(){
				$(this).parent().parent().remove();
			});
		});
	</script>
</head>

<body>
	<!--Content Section -->
	<div id="content_sec">
		<div id="left_content">
			<div class="video-category" id="tab1">
				<div  class="heading-list-edit"><h1><%= @page_title %></h1></div>
				<% if @video.video_taggees.any? %>
					<div class="wrapper_list_view">
						<%= form_for :video, :url => "/video/#{@video.id}/update_tags#{"/new" if @new}" do |f| %>
							<div id="video_taggees">
								<table  id="edit_tags_wrappper">
									<tr>
										<td id="tag_table">
											<% @video.video_taggees.each do |video_taggee| %>
												<div class="edit_box radious_6 edit_box_center" id="video_taggee<%= video_taggee.id.to_s %>">
													<%= fields_for_taggee(video_taggee) do |tag| %>
														<div id="face_tag" class="ui-widget">
															<div class="left delete_box_tag"><%= link_to_function image_tag("gallery_delete.png", :class=>'gallery_delete'), "var node1 = document.getElementById(\'video_taggee#{video_taggee.id.to_s}\');node1.parentNode.removeChild(node1)" %></div>
															<div class="image_border radious_6"><img class="gallary_image" src="<%= "#{video_taggee.img_path}" %>" width="80" height="80"></div>
															<label for="tags">Who is this? </label>
															<br><!-- Moozly: don't mess with these 2 inputs positioning, I'm handling them in jquery as .next() -->
																<%= tag.text_field :contact_info, :class => "contact_info" %>
																<%= tag.hidden_field :fb_id, :class =>"fb_id" %>
															<br>
														</div>
													<% end %>
												</div>
											<% end %>
										</td>
									</tr>
								</table>
								<a class="radious_6" id="add_new_tag">Add another Vtag</a>
								<br>
								<br class="clear" />
								<div id="updade_footer">
									<div><input class="site_button radious_6" type="submit" onclick = "update_fb_ids();" value="Update video" name="commit"></div>
								</div>
							</div>
						<% end %>
					</div>
				<% else %>			
					<h2> Sorry, no faces found in this video </h2>
					<br class="clear" />
					<div>
						<p><input type="button" onclick="location.href='<%= @video.uri %>'" value="Back" name="back"></p>
					</div>		
				<% end %>
			</div>
		</div>
		<%= render :partial => "sidebars/single_video_sidebar" %>
    <br class="clear" />
	</div>
  <!--Content Section End -->
 </div>
</body>

<script type="text/javascript">
	$(function() {
		var availableTags = <%= raw @names_arr.to_json %>;
		var contacts = document.getElementsByClassName("contact_info");
		$(contacts).autocomplete({
			source: availableTags
		});
	});

	//$(function() {
	//		var availableTags = <%#= raw @names_arr.to_json %>;
	//		var contacts = document.getElementsByClassName("contact_info"); 		
	//		this function display the JQuery ui autocomplite+image
	//	$(".contact_info").each(function() {
	//			$(this).autocomplete({
	//			source: availableTags;
	//			source: [
	//			<%# @friends.each do |f|%>
	//           {
	//               value:'<%#=f[0]%>',
	//                id: '<%#=f[1]%>'               
	//            },
	//            <#% end %>
	//       ],
	//       minLength: 1	
	//			}).data("autocomplete")._renderItem = function (ul, item) { // this section was added by pnina this is the place where the image is added to the autocomplite
	//				return $("<li />")
	//				.data("item.autocomplete", item)
	//				.append("<a><img class=friends_pic src=https://graph.facebook.com/" +item.id+ "/picture/ width=23 height=23>" + item.value + "</a>")				
	//				.appendTo(ul);
	//			}; data
	//		});
	//	});

	var friends_hash = <%= raw @friends.to_json %>;
	function update_fb_ids(){
		$(".contact_info").each (function() {
			var fb_id_field = $(this).next();
			fb_id_field.val(friends_hash[$(this).val()]);
		});
	}
</script>

app/views/videos/edit_video.erb
TBD

app/views/videos/index.html.erb
<h2>Videos</h2><br />

<%= link_to 'New Video', new_video_url %><br />
<% for video in @videos do %>
  <p><%= link_to video.title, video %></p>
<% end %>

app/views/videos/list.html.erb
<head>
	<title>VtagO - <%= @page_title %> Videos</title>
</head>
<body>
	<!--Content Section -->

	<div id="content_sec">
		<div id="left_content">
			<div id="banner_slider">
				<div id="nav-slider">
					<ul>
						<li class= <%= @order == "latest" ? "active" : "nobg" %> ><a href="/video/latest">Latest Videos </a></li>
						<li class= <%= @order == "most popular" ? "active" : "nobg" %>><a href="/video/most_popular"> Most Popular</a></li>
						<% if @category %>
						 <li class='active'><a href=#> <%= @page_title %> </a></li>
						<% end %>
					</ul>
				</div>
				<%= render :partial => "videos/player_frame" %>	
			</div>
			<%= render :partial => "videos/videos_list" %>
			<%= render :partial => "sidebars/list_sidebar" %>

      <br class="clear" />
		</div>
    	<!--Content Section End -->
   </div>
</body>

app/views/videos/user_videos_list.html.erb
<head>
	<title>VtagO - <%= @page_title %> Videos</title>
</head>
<body>
	<!--Content Section -->

	<div id="content_sec">
		<div id="left_content">
			<%= render :partial => "videos/videos_list" %>
			<%= render :partial => "sidebars/single_video_sidebar" %>
	<br class="clear" />
</div>
<!--Content Section End -->

</body>